yakbak/views.py
from contextlib import suppress
import logging
import uuid

from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import login_required, login_user, logout_user
from flask_wtf import FlaskForm
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import NoResultFound
from werkzeug.wrappers import Response

from yakbak import mail
from yakbak.auth import get_magic_link_token_and_expiry, parse_magic_link_token
from yakbak.forms import (
    ConductReportForm,
    DemographicSurveyForm,
    EmailAddressForm,
    SpeakerEmailForm,
    TalkForm,
    UserForm,
    VoteForm,
)
from yakbak.models import (
    Category,
    ConductReport,
    db,
    DemographicSurvey,
    InvitationStatus,
    Talk,
    TalkCategory,
    TalkSpeaker,
    TalkStatus,
    UsedMagicLink,
    User,
    Vote,
)
from yakbak.view_helpers import (
    requires_new_proposal_window_open,
    requires_proposal_editing_window_open,
    requires_review_allowed,
    requires_voting_allowed,
)

app = Blueprint("views", __name__)
logger = logging.getLogger("views")


def load_talk(talk_id: int) -> Talk:
    talk = Talk.query.get_or_404(talk_id)
    if g.user not in [s.user for s in talk.speakers]:
        # TODO: figure out how to do this in the query directly?
        abort(404)

    return talk


@app.route("/")
def index() -> Response:
    return render_template("index.html")


@app.route("/login")
def login() -> Response:
    auth_methods = current_app.settings.auth.auth_methods()
    return render_template("login.html", auth_methods=auth_methods)


@app.route("/logout")
def logout() -> Response:
    logout_user()
    return redirect(url_for("views.index"))


@app.route("/login/email", methods=["GET", "POST"])
def email_magic_link() -> Response:
    form = EmailAddressForm()
    if form.validate_on_submit():
        token, expiry = get_magic_link_token_and_expiry(form.email.data)
        url = url_for(
            "views.email_magic_link_login", magic_link_token=token, _external=True
        )
        mail.send_mail(
            to=[form.email.data],
            template="email/magic-link",
            magic_link=url,
            magic_link_expiration=expiry,
        )
        return redirect(url_for("views.email_magic_link_done"))
    return render_template("email_magic_link.html", form=form)


@app.route("/login/email/sent")
def email_magic_link_done() -> Response:
    return render_template("email_magic_link_sent.html")


@app.route("/login/token/<magic_link_token>")
def email_magic_link_login(magic_link_token: str) -> Response:
    try:
        used_magic_link = UsedMagicLink(token=magic_link_token)
        db.session.add(used_magic_link)
        db.session.commit()
    except IntegrityError:
        # race condition, UsedMagicLink row exists
        db.session.rollback()
        return current_app.response_class(
            render_template("email_magic_link_used.html"), status=401
        )

    verified_email = parse_magic_link_token(magic_link_token)
    if verified_email is None:
        abort(404)

    user = User.query.filter_by(email=verified_email).first()
    if user:
        login_user(user)
        return redirect(url_for("views.talks_list"))

    user = User(email=verified_email, fullname=verified_email)
    db.session.add(user)
    db.session.commit()
    login_user(user)
    flash("Welcome! Please tell us your name.")
    return redirect(url_for("views.user_profile"))


@app.route("/profile", methods=["GET", "POST"])
@login_required
def user_profile() -> Response:
    user = g.user
    form = UserForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("views.index"))

    return render_template("profile.html", form=form)


@app.route("/talks")
@login_required
def talks_list() -> Response:
    talks = [ts.talk for ts in g.user.talks if ts.state == InvitationStatus.CONFIRMED]
    proposed_talks = [t for t in talks if t.state == TalkStatus.PROPOSED]
    withdrawn_talks = [t for t in talks if t.state == TalkStatus.WITHDRAWN]

    invitations = TalkSpeaker.query.filter(
        TalkSpeaker.user == g.user,
        TalkSpeaker.state != InvitationStatus.CONFIRMED,
        TalkSpeaker.state != InvitationStatus.DELETED,
    ).all()
    speaker_actions = {
        InvitationStatus.PENDING: [
            ("Reject", "danger", "views.reject_invite"),
            ("Accept", "primary", "views.accept_invite"),
        ],
        InvitationStatus.REJECTED: [("Accept", "primary", "views.accept_invite")],
    }
    talk_actions = {
        TalkStatus.PROPOSED: [("Withdraw", "danger", "views.withdraw_proposal")]
    }
    if g.conference.creating_proposals_allowed:
        # you can resubmit talks only until the end of the CFP window
        talk_actions[TalkStatus.WITHDRAWN] = [
            ("Re-Submit", "primary", "views.resubmit_proposal")
        ]

    prompt_for_survey = proposed_talks and not g.user.demographic_survey
    prompt_for_bio = proposed_talks and not g.user.speaker_bio
    return render_template(
        "talks_list.html",
        proposed_talks=proposed_talks,
        withdrawn_talks=withdrawn_talks,
        num_talks=len(proposed_talks),
        invitations=invitations,
        speaker_actions=speaker_actions,
        talk_actions=talk_actions,
        prompt_for_survey=prompt_for_survey,
        prompt_for_bio=prompt_for_bio,
        TalkStatus=TalkStatus,
    )


@app.route("/talks/<int:talk_id>", methods=["GET", "POST"])
@requires_proposal_editing_window_open
@login_required
def edit_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    form = TalkForm(conference=g.conference, obj=talk)
    if form.validate_on_submit():
        form.populate_obj(talk)
        talk.reset_after_edits()
        db.session.add(talk)
        db.session.commit()
        return redirect(url_for("views.preview_talk", talk_id=talk.talk_id))

    return render_template("edit_talk.html", talk=talk, form=form)


@app.route("/talks/<int:talk_id>/anonymized", methods=["GET", "POST"])
@login_required
def anonymized_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    if not talk.is_anonymized:
        flash("This talk has not yet been anonymized for review")

    return render_template("anonymized_talk_preview.html", talk=talk)


@app.route("/talks/<int:talk_id>/withdraw")
@login_required
def withdraw_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.WITHDRAWN
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} withdrawn")
    return redirect(url_for("views.talks_list"))


@app.route("/talks/<int:talk_id>/resubmit")
@requires_new_proposal_window_open
@login_required
def resubmit_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.PROPOSED
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} re-submitted")
    return redirect(url_for("views.talks_list"))


@app.route("/vote")
@requires_voting_allowed
@login_required
def vote_home() -> Response:
    """Render the voting homepage with talk categories."""
    # TODO: When this is multitenant, categories and votes should be filtered
    # by event.
    categories = Category.query.filter_by(conference=g.conference).order_by(
        Category.name.asc()
    )
    # TODO: This is an inefficient way to do this. Write it as one query
    # instead.
    categories_counts = {
        category: Talk.query.join(TalkCategory)
        .filter(
            Talk.state == TalkStatus.PROPOSED,
            Talk.talk_id.notin_(
                db.session.query(Vote.talk_id).filter(
                    Vote.user == g.user, Vote.value != None  # noqa: E711
                )
            ),
            TalkCategory.category_id == category.category_id,
        )
        .count()
        for category in categories
    }

    votes = Vote.query.filter_by(user=g.user).order_by(Vote.created.asc())
    return render_template(
        "vote/home.html",
        categories_counts=categories_counts,
        clear_skipped_form=FlaskForm(),
        votes=votes,
        vote_label_map=VoteForm.VOTE_VALUE_CHOICES,
    )


@app.route("/vote/category/<int:category_id>")
@requires_voting_allowed
@login_required
def vote_choose_talk_from_category(category_id: int) -> Response:
    """Display a talk in need of a vote.

    If a talk has already been displayed for voting and is included in
    the selected category, but has not been voted on or explicitly
    skipped, it should be used. This is independent of the chosen
    category.  Otherwise choose fairly from a list of possible talks.

    The talk list:

    1. is filtered down to the requested category
    2. excludes talks that a user has previously voted on or skipped
    3. is sorted to attempt to evenly distribute votes across talks

    .. note::
        Because talks can belong to more than one category, ensuring
        that votes are evenly distributed is not quite possible.
        Breaking the list up by category is a tradeoff to allow voters
        to weigh in on topics they have interest or expertise in. This
        implementation should still ensure that all proposals have
        enough votes to derive meaningful signal.

    """
    category = Category.query.filter_by(
        category_id=category_id, conference=g.conference
    ).first_or_404()

    vote = (
        db.session.query(Vote)
        .join(Talk)
        .join(TalkCategory)
        .filter(
            TalkCategory.category_id == category.category_id,
            Vote.skipped == None,
            Vote.user == g.user,
            Vote.value == None,  # noqa: E711
        )
        .first()
    )

    if vote is None:
        talk = (
            db.session.query(Talk)

yakbak/templates/action_not_allowed.html
{% extends "base.html" %}

{% block container %}
<div class="row">
  <div class="col">
    {% if action == "create_proposal" or action == "edit_proposal" %}
    <h2>{{ g.conference.informal_name }} CFP is Over</h2>
    <p>
    Unfortunately, the {{ g.conference.informal_name }} call for proposals
    is over. We appreciate your interest, but we cannot accept new proposals
    at this time.
    </p>
    {% if action == "edit_proposal" %}
    <p>
    Additionally, talk editing is disabled at this time while we review
    talks for selection in {{ g.conference.informal_name }}.
    </p>
    {% endif %}
    {% endif %}
    {% if action == "vote" %}
    <h2>
      {{ g.conference.informal_name }} Voting has
      {% if g.conference.voting_window_after_now %}
        not started yet
      {% else %}
        ended
      {% endif %}
    </h2>

    <p>
    Unfortunately, voting on proposals for {{ g.conference.informal_name }} has
    ended. We appreciate the time that you have taken to vote so far. Your input
    helps us make {{ g.conference.informal_name }} as good as it can be!
    </p>
    {% endif %}
    {% if action == "review" %}
    {% if g.conference.review_window_after_now %}
    <h2>{{ g.conference.informal_name }} Voting Review Has Not Started</h2>
    <p>
    Unfortunately, the {{ g.conference.informal_name }} vote review period
    has not started yet.
    </p>
    {% else %}
    <h2>{{ g.conference.informal_name }} Voting Review Is Over</h2>
    <p>
    Unfortunately, the {{ g.conference.informal_name }} vote review period
    has finished.
    </p>
    {% endif %}
    {% endif %}
    <p>
    <a class="btn btn-primary" href="{{ url_for("views.talks_list") }}">Back to talks list</a>
    </p>
  </div>
</div>
{% endblock %}

yakbak/templates/demographic_survey_done.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Demographic Survey - {{ super() }}{% endblock %}

{% block container %}
<div class="row">
  <div class="col-md-8">
    {% if optout %}
    <h1>You Have Opted Out of the PyGotham Demographic Survey</h1>
    <p>
    If you change your mind, you can always return here from your
    <a href="{{ url_for("views.user_profile") }}">profile</a>
    </p>
    {% else %}
    <h1>Thanks For Completing the PyGotham Demographic Survey</h1>
    <p>
    You can always edit your responses from your
    <a href="{{ url_for("views.user_profile") }}">profile</a>.
    </p>
    {% endif %}
</div>
{% endblock %}

yakbak/templates/edit_speakers.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Speakers for {{ talk.title }} - {{ super() }}{% endblock %}

{% block container %}
<div class="row py-3">
  <div class="col">
    <h3>Speakers for {{ talk.title }}:</h3>
  </div>
</div>
{% for talk_speaker in talk.speakers %}
  {% set speaker = talk_speaker.user %}
  {% set state = talk_speaker.state %}
  <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %} speaker">
    <div class="col-md-7">{{ speaker.fullname }} ({{ speaker.email }})</div>
    <div class="col-md-3 text-right">{{ state.name|title }}</div>
    <div class="col-md-2 text-right">
      {% for label, cls, view in actions[state] %}
      <a href="{{ url_for(view, talk_id=talk.talk_id, user_id=speaker.user_id) }}" class="btn btn-outline-{{ cls }} btn-sm">{{ label }}</a>
      {% endfor %}
    </div>
  </div>
{% endfor %}
<form method="POST">
  <div class="row py-2">
    <div class="col-md-10">
      {{ macros.render_field(form.email, "user@example.com") }}
      {{ macros.render_error(form.email) }}
    </div>
    <div class="col-md-2 text-right">
      <button class="btn btn-primary btn-block" type="submit">Invite Speaker</a>
    </div>
  </div>
  {{ form["csrf_token"] }}
</form>
<div class="row">
  <div class="col text-right">
    <small><a href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">Return to {{ talk.title }}</a></small>
  </div>
</div>
{% endblock %}

yakbak/templates/email_magic_link_used.html
{% extends "base.html" %}

{% block title %}Invalid Login Link - {{ super() }}{% endblock %}

{% block container %}
<p>
That magic link is invalid. You can <a href="{{ url_for("views.email_magic_link") }}">create another</a>
or <a href="{{ url_for("views.login") }}">choose another login method</a>.
</p>
{% endblock %}

yakbak/templates/index.html
{% extends "base.html" %}

{% block morestyles %}
<style type="text/css">
  .jumbotron {
    background-color: #50484f;
    padding: 1rem;
  }
  .jumbotron img {
    max-width: 30%;
    margin-left: 2rem;
  }
  .jumbotron h1, .jumbotron a:not(.btn), .jumbotron a:not(.btn):visited {
    color: #9ece29;
  }
  .jumbotron {
    color: white;
</style>
{% endblock %}

{% block metas %}
{{ super() }}
    <meta name="twitter:card" content="summary_large_image">
    {% if g.conference.creating_proposals_allowed %}
    <meta name="twitter:title" content="{{ g.conference.informal_name }} Call for Proposals is Open!">
    <meta name="twitter:description" content="If you have something that Pythonistas want to hear about, propose a talk! {{ g.conference.informal_name }} CFP open through {{ g.conference.proposals_end.strftime('%B %d') }}.">
    {% elif g.conference.voting_allowed %}
    <meta name="twitter:title" content="Vote on {{ g.conference.informal_name }} Talk Proposals!">
    <meta name="twitter:description" content="Help us pick the talks that will end up in {{ g.conference.informal_name }}! Cast your vote through {{ g.conference.voting_end.strftime('%B %d') }}">
    {% else %}
    <meta name="twitter:title" content="{{ g.conference.informal_name }} Call for Proposals">
    <meta name="twitter:description" content="The {{ g.conference.informal_name }} Call for Proposals isn't active right now{% if g.conference.twitter_username %} -- follow {{ g.conference.twitter_username }} for conference announcements{% endif %}.">
    {% endif %}
    <meta name="twitter:image" content="{{ url_for("static", filename="pygotham-twitter-card.jpg", _external=True) }}">
    <meta name="twitter:image:alt" content="{{ g.conference.full_name }} Logo">
    {% if g.conference.twitter_username %}
    <meta name="twitter:creator" content="@{{ g.conference.twitter_username }}">
    <meta name="twitter:site" content="@{{ g.conference.twitter_username }}">
    {% endif %}
{% endblock %}

{% block container %}
<div class="jumbotron">
  <img src="{{ url_for("static", filename="pygotham-logo.svg") }}" align="right">
  <h1 class="display-4">Call for Proposals</h1>
  <p class="lead">
  Everyone, no matter their job, age, background, or level of experience has
  something interesting to share. Even you! You've developed a technique, or
  discovered a library, squashed a bug or solved a problem. Whatever it may
  be, {{ g.conference.full_name }} wants to hear your story. Won't you share
  it with us?
  </p>
  {% if g.conference.creating_proposals_allowed %}
  <p>
    <strong>There's still time!</strong>
    Our Call for Proposals is open through May 12, <a href="https://time.is/Anywhere_on_Earth">Anywhere on Earth</a>.
  </p>
  <br>
  <a class="btn btn-lg btn-light border" href="{{ url_for("views.create_talk") }}">
    {% if g.user.is_anonymous %}Log In and{%endif %}
    Submit a Talk Now
  </a>
  {% elif g.conference.voting_allowed %}
  <p>
    <strong>Help us pick the talks that make the conference!</strong>
    Cast your votes to tell us whic talks you'd like to see at {{ g.conference.informal_name }}.
  </p>
  <a class="btn btn-lg btn-light border" href="{{ url_for("views.vote_home") }}">
    {% if g.user.is_anonymous %}Log In and{%endif %}
    Vote Now
  </a>
  {% else %}
  <p>
    Unfortunately, our Call for Proposals is over.
    {% if g.conference.voting_window_after_now %}
    We're anonymizing all the proposals, and getting ready to start voting
    on {{ g.conference.voting_window.start.strftime("%A, %B %d") }}.
    {% else %}
    For the latest information about {{ g.conference.informal_name }}, head to
    <a href="{{ g.conference.website }}">the main {{ g.conference.informal_name }} site</a>.
    {% endif %}
  </p>
  {% endif %}
  <br style="clear:both">
</div>
<div class="row py-3">
  <div class="col">
    <h2>About {{ g.conference.full_name }}</h2>

    <p>{{ g.conference.full_name }} is taking place from October 4-5 at the Hotel Pennsylvania
    in New York City. It will feature three tracks of talks on Friday, October
    4th and Saturday, October 5th.</p>

    <h3>Background</h3>

    <p>PyGotham is a New York City based, eclectic, Py-centric conference
    covering many topics. There’s a diverse speaker list, and some things which
    will be quite different. PyGotham attracts developers of various
    backgrounds and skill levels from the New York metropolitan area and
    beyond. Activities include two full days of talks, lightning talk sessions,
    and a social event.</p>

    <h3>History</h3>

    <p>PyGotham began in 2011 and was comprised largely of the NYC Python
    community. Since then, the conference has taken place (almost) every year
    and grown significantly. While the conference has gotten larger, PyGotham
    has always been and remains a conference for developers and run by
    developers.</p>

    <h3>Who?</h3>

    <p>PyGotham is a production of <a href="https://bigapplepy.org/">Big Apple Py</a>
    and made possible by a very generous and overworked group of volunteers.
    To reach them, send a message to
    <a href="mailto:organizers@pygotham.org">organizers@pygotham.org</a>.</p>


    <h2>Who should submit? What topics are OK?</h2>

    <p>Anyone interested in speaking is encouraged to submit a proposal. There
    are no restrictions on topics, but we recommend they be of interest to
    Pythonistas. Talks will fill slots of 25 minutes and 40 minutes, including
    time for questions and answers.</p>

    <p>Everyone is encouraged to submit a proposal. We are looking for speakers
    of all different speaking and Python experience levels, from first-timers
    to experienced veterans.</p>

    <p>The audience’s experience level will be just as diverse, so feel free to
    cater your talk to a specific experience level.</p>

    <h3>Looking for Ideas?</h3>

    <p>One of the best ways to come up with an idea is to think about something
    you want to learn about. It’s a great way to learn about the topic and
    you’ll be able to share your experiences with the audience.</p>

    <p>Another great source of topics is challenges you’ve recently overcome.
    Did you recently use a unique profiler to identify a performance
    bottleneck? Perhaps you had to dive deep into a protocol or library and
    discovered something everyday users might not know. Experiences like these
    are usually full of great tips and tricks to share.</p>

    <p>Still looking for ideas? Here are some ideas to help get you started:</p>

    <ul>
      <li>What’s new in web frameworks in 2019</li>
      <li>How to design software for safety and reliability</li>
      <li>Ethics of big data and software development</li>
      <li>Effective use of linters and other static analysis tools</li>
      <li>Recent changes to standard Python tools</li>
    </ul>

    <p>Also see the talks from
    <a href="https://2018.pygotham.org/talks/">2018</a>,
    <a href="https://2017.pygotham.org/talks/">2017</a>, and
    <a href="https://2016.pygotham.org/talks/">2016</a> for ideas.</p>

    <h3>Talk Selection</h3>

    <p>PyGotham’s talk review process encompasses two phases: immediately after
    the CFP closes, we will have a round of public, anonymous voting, so that
    we can get a feel for which of the talks are of greatest interest to our
    audience. After that, the program committee will assemble the final
    schedule using the ratings as a guide.</p>

    <p>We will share information on how to sign up for voting and the program
    committee on pygotham.org near the end of the CFP.</p>

    {% if g.user.is_anonymous %}
    <h2>OK, I'm sold!</h2>

    <p>
    Fantastic! If you have an idea, turning it into a proposal is a
    snap -- why not <a href="{{ url_for("views.create_talk") }}">submit
    a talk</a> right now?
    </p>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

yakbak/templates/preview_talk.html
{% extends "base.html" %}

{% block title %}Preview "{{ talk.title|default("Talk") }}" - {{ super() }}{% endblock %}

{% block container %}
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col"><h1>{{ talk.title }}</h1></div>
      <div class="w-100"></div>
      <div class="col"><h4>{{ talk.length }} Minutes</h2></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col">
        {{ talk.description|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Outline:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.outline|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Audience Take-Aways:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.take_aways|markdown }}
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <em class="text-muted">Reviewers will see voting instructions here.</em>
  </div>
</div>
<div class="row py-3">
  <div class="col">
    <a class="btn btn-primary" href="{{ url_for("views.talks_list") }}">Save &amp; Return</a> or
    <a class="btn btn-light border" href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">Edit Again</a>
  </div>
</div>
{% endblock %}

yakbak/templates/talks_list.html
{% extends "base.html" %}

{% block title %}Talks - {{ super() }}{% endblock %}

{% macro vitals(talk) %}
{% set speakers = talk.speakers|map(attribute="user") %}
{% set other_speakers = speakers|remove(user)|map(attribute="fullname")|list %}
{% if other_speakers|length > 1 %}
({{ talk.length }} Minutes, {{ other_speakers|join(", ") }}, and You)
{% elif other_speakers|length == 1 %}
({{ talk.length }} Minutes, {{ other_speakers|join("") }} and You)
{% else %}
({{ talk.length }} Minutes)
{% endif %}
{% endmacro %}

{% block container %}
{% if prompt_for_survey %}
<div class="alert alert-info" role="alert">
  <p class="mt-3">Thanks for submitting {% if num_talks == 1 %}a talk{% else %}talks{% endif %}!
  In order to help us ensure a diverse and inclusive {{ g.conference.informal_name }},
  please consider filling out the <a href="{{ url_for("views.demographic_survey") }}">demographic
  survey</a>.</p>
  <p>You may <a href="{{ url_for("views.demographic_survey_opt_out") }}">opt
  out</a> to dismiss this message.</p>
</div>
{% endif %}
{% if prompt_for_bio %}
<div class="alert alert-info" role="alert">
  <p class="mt-3">Thanks for submitting {% if num_talks == 1 %}a talk{% else %}talks{% endif %}!
  Please add a <a href="{{ url_for("views.user_profile") }}">speaker biography</a> to your profile,
  for inclusion in the conference program.
  </p>
</div>
{% endif %}

{% macro talk_table(talks) %}
{% for talk in talks %}
  <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %}">
    <div class="col-md-7 talk">
      <a href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">{{ talk.title|truncate(100) }}</a>
      {{ vitals(talk) }}
    </div>
    <div class="col-md-5 text-right">
      Updated {{ talk.updated|timesince }}
      <a href="{{ url_for("views.edit_speakers", talk_id=talk.talk_id) }}" class="btn btn-outline-primary btn-sm ml-2">Manage Speakers</a>
      {% for label, cls, view in talk_actions[talk.state] %}
      <a href="{{ url_for(view, talk_id=talk.talk_id) }}" class="btn btn-outline-{{cls}} btn-sm">{{ label }}</a>
      {% endfor %}
    </div>
    {% if talk.has_anonymization_changes %}
    <div class="col-md-12 mt-2">
      <div class="alert alert-warning my-0 pt-1 pb-2" role="alert">
        <small>
        This talk has anonymization changes. Please <a href="{{ url_for("views.anonymized_talk", talk_id=talk.talk_id) }}">review
        the anonymized version</a>, and consider updating your talk for
        anonymous review.
        </small>
      </div>
    </div>
    {% endif %}
  </div>
{% endfor %}
{% endmacro %}

{% set has_proposed_talks = proposed_talks|length > 0 %}
{% set has_withdrawn_talks = withdrawn_talks|length > 0 %}

<div class="row py-3">
  <div class="col">
    <h3>{% if has_withdrawn_talks %}Proposed {% endif %}Talks:</h3>
    {% if has_proposed_talks %}
    {{ talk_table(proposed_talks) }}
    {% else %}
    <div class="row py-2 border-top border-right border-left border-bottom">
      <div class="col-md-12">
        <em>
          No talks yet.
          {% if g.conference.creating_proposals_allowed %}
            Why not <a href="{{ url_for("views.create_talk") }}">add one now?</a>
          {% endif %}
        </em>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% if g.conference.creating_proposals_allowed %}
<div class="row py-2">
  <div class="col text-right">
    <a class="btn btn-primary" href="{{ url_for("views.create_talk") }}">Add Talk</a>
  </div>
</div>
{% endif %}
{% if has_withdrawn_talks %}
<div class="row py-3">
  <div class="col">
    <h3 class="my-3">Withdrawn Talks:</h3>
    <p><em>Withdrawn talks will not be considered for inclusion in {{ g.conference.informal_name }}.</em></p>
    {{ talk_table(withdrawn_talks) }}
  </div>
</div>
{% endif %}

{% if invitations|length > 0 %}
  <div class="row py-3">
    <div class="col">
      <h3>Speaker Invitations:</h3>
    </div>
  </div>
  {% for invitation in invitations %}
    <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %}">
      <div class="col-md-9 talk">
        {{ invitation.talk.title|truncate(100) }}
        {{ vitals(invitation.talk) }}
      </div>
      <div class="col-md-3 text-right">
        {% for label, cls, view in speaker_actions[invitation.state] %}
        <a href="{{ url_for(view, talk_id=invitation.talk.talk_id) }}" class="btn btn-outline-{{cls}} btn-sm">{{ label }}</a>
        {% endfor %}
      </div>
    </div>
  {% endfor %}
  <div class="row py-2">
    <div class="col text-right">
      <a class="btn btn-primary" href="{{ url_for("views.create_talk") }}">Add Talk</a>
    </div>
  </div>
{% endif %}
{% endblock %}